version: 2.1

anchors:
  context: &context
    context: shared

  default_job_config: &default_job_config
    working_directory: /home/circleci/plugin
    machine:
      image: ubuntu-2004:202201-02

jobs:
  build_package_release:
    <<: *default_job_config
    steps:
      - checkout
      - run:
          name: Getting GravityKit test/build tools
          command: |
            git clone git@github.com:GravityKit/Tooling.git /home/circleci/tooling
      - run:
          name: Building and packaging
          command: |
            /home/circleci/tooling/build-tools/build_tools.sh composer -o "build"
            rm -rf src
            if [ "${CIRCLE_BRANCH}" != "main" ]; then
              /home/circleci/tooling/build-tools/build_tools.sh package_build -o "gf-entries-in-excel gfexcel.php --include-hash"
            else
              /home/circleci/tooling/build-tools/build_tools.sh package_build -o "gf-entries-in-excel gfexcel.php $([[ $(git log -n 1 | grep "\[skip release\]") ]] && echo --include-hash)"
            fi
            mkdir -p gf-entries-in-excel
            rm -rf build/composer.* build/strauss.phar
            cp -R build gf-entries-in-excel
            zip -gr $(ls gf-entries-in-excel-*.zip) gf-entries-in-excel
            mkdir .release
            cp gf-entries-in-excel-*.zip .release
      - run:
          name: Creating a GitHub release
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              git config user.email "support@gravitykit.com"
              git config user.name "GravityKit - CI"
              /home/circleci/tooling/build-tools/build_tools.sh create_release -o "gfexcel.php $(ls gf-entries-in-excel-*.zip)"
            fi
      - run:
          name: Notifying GravityKit Release Manager
          command: |
            if ! [[ $(git log -n 1 | grep "\[skip notify\]") ]]; then
              /home/circleci/tooling/build-tools/build_tools.sh announce_build -o "gfexcel.php $(ls gf-entries-in-excel-*.zip) --with-circle"
            fi
      - store_artifacts:
          path: .release
          destination: release

workflows:
  version: 2
  test_and_package:
    jobs:
      - build_package_release:
          <<: *context
